# **Basic Tensor operations**

In [ ]:
import torch

In [ ]:
# tensor : a no., matrics, vector, array
ts = torch.tensor(8.0) # scalar
ts

tensor(8.)

In [ ]:
ts.dtype

torch.float32

In [ ]:
tv = torch.tensor([1.0,2.0,3.0]) # vector
tv

tensor([1., 2., 3.])

In [ ]:
tm = torch.tensor([[1,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]]) # matrics
tm

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# passing list of lists
td = torch.tensor([[[1,2,3],[4.0,5,6]],             # 3d array
                   [[12,13,14.0],[15,16,17.0]],
                   [[0,9,3],[4,7,2]]
])
td

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[12., 13., 14.],
         [15., 16., 17.]],

        [[ 0.,  9.,  3.],
         [ 4.,  7.,  2.]]])

In [ ]:
td.dtype

torch.float32

All the elements in the tensors are in float as the integer values may create problem during several mathematical operation and gradient calculation.

In [ ]:
# getting shape
# in output ....if 1-d  then 1 element in shape.
ts.shape # 0 element (as single value)

torch.Size([])

In [ ]:
tv.shape # 1 element...1_d

torch.Size([3])

In [ ]:
tm.shape # 2d ...3 rows x 3 columns

torch.Size([3, 3])

In [ ]:
td.shape # 3d .....

torch.Size([3, 2, 3])

In [ ]:
## problem  (if nd tensor has no proper shape)
# tx = torch.tensor([
#     [1,2,4],
#     [3,9]
# ])
# tx


# Output:
# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# <ipython-input-18-6f7f5ced3ff3> in <module>
#       2 tx = torch.tensor([
#       3     [1,2,4],
# ----> 4     [3,9]
#       5 ])
#       6 tx

# ValueError: expected sequence of length 3 at dim 1 (got 2)

In [ ]:
# here we are not interested to get the gradients wrt x.
x = torch.tensor(3.0)
w = torch.tensor(4.0,requires_grad = True)
b = torch.tensor(5.0, requires_grad= True)
print(x,w,b)

tensor(3.) tensor(4., requires_grad=True) tensor(5., requires_grad=True)


In [ ]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# # invoke the deivatives of y 
y.backward() # will store derivative (grdaients) of y wrt all the input tensors to the .grad property of respective tensors.

In [ ]:
x.grad  # dy/dx # gradients wrt x ### we got nothing because at x, we have not set requires grad = True

In [ ]:
w.grad # dy/dw  # gradients wrt w

tensor(3.)

In [ ]:
b.grad # dy/db  # gradients wrt b

tensor(1.)

In [ ]:
# torch functions
tf = torch.full((2,3),33) # a tensor filled with given value in specified shape. (arguments: shape, value)
tf

tensor([[33, 33, 33],
        [33, 33, 33]])

In [ ]:
t1 = torch.tensor([[1,2],[3,4],[5,6]])
t2 = torch.tensor([[7,8],[9,10]])
tc = torch.cat((t1,t2)) # join two tensors with compatible shape
tc

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
tsine = torch.sin(t1) # get sine value of t1
tsine

tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568],
        [-0.9589, -0.2794]])

In [ ]:
treshape = tsine.reshape(3,2,1) # reshaping tensor in a compatible size
treshape

tensor([[[ 0.8415],
         [ 0.9093]],

        [[ 0.1411],
         [-0.7568]],

        [[-0.9589],
         [-0.2794]]])

In [ ]:
# numpy is a popular python lib used for scientific and mathematical calculation in python.

import numpy as np
x = np.array([[1,2,3.0],[4,5,6.0]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
y = torch.from_numpy(x) # convert numpy to tensor
y

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [ ]:
z = y.numpy() # convert tensor to numpy 
z

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
# Since numpy has been already utilised for handling multidimension arrays and providing several datastructure, why we need pytorch tensor??
#  because of 2 reasons: pytorch has- 
# (1) Autograd : automatically calculate gradients for tensor operations (essential for training DNN)
# (2) GPUs : tensor operations can be easily handled by GPUS, performing high computational operations.

# **Gradient Decent & Linear Regression**

In [ ]:
import torch
import numpy as np

## Required eq. for basic Linear Regression modeling

yield_apples = w11 * temp + w12 * rainfall + w13 * humidity + b1

yield_oranges = w21 * temp + w22 * rainfall + w23 * humidity + b2

In [ ]:
# input--> temp., rainfall, humidity
inputs = np.array([[73, 67, 43],
                       [91,88,64],
                       [87,134,58],
                       [102,43,37],
                       [69,96,70]], dtype='float32')

In [ ]:
# targets--> yielding apples, oranges
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]
                    ],dtype = 'float32')

In [ ]:
# convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
inputs,targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

### weights and biases

In [ ]:
# create weights and bias
# w size is 2 X 3 (targets count, input counts) 
# b size is 2 X 1 (targets counts) 

w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
w,b

(tensor([[ 1.7815, -1.6992,  0.9434],
         [ 0.8937,  1.0086, -0.5165]], requires_grad=True),
 tensor([0.3001, 0.2122], requires_grad=True))

In [ ]:
# Y = X * W^T + b (linear regression) ...Y is prediction

### predictions

In [ ]:
inputs @ w.t() + b  # (pred of the model for apples and oranges)

tensor([[ 57.0739, 110.8209],
        [ 73.2701, 137.2421],
        [-17.6777, 183.1601],
        [143.8584, 115.6330],
        [ 26.1431, 122.5493]], grad_fn=<AddBackward0>)

In [ ]:
def model(x):
  return x @ w.t() + b

In [ ]:
# generate predictions
preds = model(inputs)
preds

tensor([[ 57.0739, 110.8209],
        [ 73.2701, 137.2421],
        [-17.6777, 183.1601],
        [143.8584, 115.6330],
        [ 26.1431, 122.5493]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
# large error between preds and target as we star our model with random 
#inilitalsation of w and b.

### Loss 

In [ ]:
diff = preds - targets
mse = torch.sum(diff * diff)/diff.numel()
mse # this value tells us how badly our model is performing

tensor(5118.9761, grad_fn=<DivBackward0>)

In [ ]:
# MSE loss
def mse(t1,t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel() # numel() fn gives no. of elements in ny metrics.

In [ ]:
# compute loss
loss = mse(preds, targets)
loss

tensor(5118.9761, grad_fn=<DivBackward0>)

### compute gradients

In [ ]:
loss.backward()

In [ ]:
w

tensor([[ 1.7815, -1.6992,  0.9434],
        [ 0.8937,  1.0086, -0.5165]], requires_grad=True)

In [ ]:
w.grad # derivatie of loss wrt w (metics with same shape as w and diff values)

tensor([[-1077.9113, -4212.2881, -1849.4128],
        [ 3781.4712,  3273.5422,  2028.3906]])

In [ ]:
b

tensor([0.3001, 0.2122], requires_grad=True)

In [ ]:
b.grad

tensor([-19.6664,  41.8811])

### Adjusting weights and biases for reducing **loss**

In [ ]:
# loss is a quardratic fn of weights and biases.
# gradients are the rate of hange of loss.
# positive slope of gradients (rate of change of loss wrt w is +ve) --> increasing the w will increase the loss and decrease the weight will decrease the loss.
# negative slope of gradients(rate of change of loss wrt w is -ve) --> increasing the w will decrease the loss and decrease the weight will increase the loss.

In [ ]:
print(w)
print(w.grad)

tensor([[ 1.7815, -1.6992,  0.9434],
        [ 0.8937,  1.0086, -0.5165]], requires_grad=True)
tensor([[-1077.9113, -4212.2881, -1849.4128],
        [ 3781.4712,  3273.5422,  2028.3906]])


In [ ]:
with torch.no_grad(): # already computed gradients so no need to compute it again.
  w -= w.grad * 1e-5  # 1e - 5 is a learning rate
  b -= b.grad * 1e-5 

In [ ]:
w #new weights

tensor([[ 1.7923, -1.6570,  0.9619],
        [ 0.8559,  0.9758, -0.5368]], requires_grad=True)

In [ ]:
b # new biases

tensor([0.3002, 0.2118], requires_grad=True)

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(4646.4409, grad_fn=<DivBackward0>)

In [ ]:
w.grad.zero_() # will reset the gradients to zero.
b.grad.zero_() # will reset the biases to zero.

tensor([0., 0.])

## Complete Trainng the model:


1.   Generate prdictions
2.   calculate loss
3.   compute gradients
4.  adjust the w and b
5. make the gradients of w and b to zero.



In [ ]:
preds = model(inputs) # 1
loss = mse(preds, targets) # 2
loss.backward() # 3
lr = 1e-5
with torch.no_grad(): 
  w -= w.grad * lr # 4 
  b -= b.grad * lr # 4
  w.grad.zero_() # 5
  b.grad.zero_() # 5

In [ ]:
loss

tensor(4646.4409, grad_fn=<DivBackward0>)

In [ ]:
# Train for 100 epochs
for i in range(100):
  preds = model(inputs) # 1
  loss = mse(preds, targets) # 2
  loss.backward() # 3
  lr = 1e-5
  with torch.no_grad(): 
    w -= w.grad * lr # 4 
    b -= b.grad * lr # 4
    w.grad.zero_() # 5
    b.grad.zero_() # 5

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(1123.7600, grad_fn=<DivBackward0>)

In [ ]:
preds # closer to target

tensor([[ 70.2707,  75.1419],
        [ 96.8159,  93.3012],
        [ 64.3993, 141.9489],
        [ 97.5473,  63.8307],
        [ 82.7707,  90.7109]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# **Linear regression using PyTorch built-in**

In [ ]:
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

### Datset and DataLoader


In [ ]:
# handling large data by dividing the data into batches 
# now perform gradient decent on each batche ...makes training faster

In [ ]:
from torch.utils.data import TensorDataset  # will picks slice of data

In [ ]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader # will create batches 

In [ ]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
# train_dl will give batches of inputs and outputs.
# Shuffling helps randmize the input so that loss will reduce faster.

In [ ]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[101.,  44.,  37.],
        [ 69.,  96.,  70.],
        [ 88., 134.,  59.],
        [ 68.,  97.,  70.],
        [ 73.,  67.,  43.]])
tensor([[ 21.,  38.],
        [103., 119.],
        [118., 132.],
        [102., 120.],
        [ 56.,  70.]])


### Create the model

In [ ]:
# nn.Linear class from pytorch initialise the weights and biases automatically.
# A pytorch's Linear layer is weights and biases matrics bundled into an object.

In [ ]:
model = nn.Linear(3,2) # args: no. of inputs, no. of outputs
model.weight

Parameter containing:
tensor([[ 0.5540, -0.3478, -0.3658],
        [-0.2157,  0.4066,  0.1125]], requires_grad=True)

In [ ]:
model.bias

Parameter containing:
tensor([-0.2993, -0.4505], requires_grad=True)

In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5540, -0.3478, -0.3658],
         [-0.2157,  0.4066,  0.1125]], requires_grad=True),
 Parameter containing:
 tensor([-0.2993, -0.4505], requires_grad=True)]

In [ ]:
preds = model(inputs)
preds

tensor([[  1.1059,  15.8852],
        [ -3.9090,  22.9043],
        [-19.9311,  41.7938],
        [ 27.7143,  -0.8014],
        [-21.0740,  31.5763],
        [  2.0077,  15.2630],
        [ -3.9270,  22.6103],
        [-19.7429,  41.6907],
        [ 26.8125,  -0.1792],
        [-21.9938,  31.9045],
        [  1.0880,  15.5912],
        [ -3.0072,  22.2821],
        [-19.9132,  42.0879],
        [ 28.6341,  -1.1296],
        [-21.9759,  32.1985]], grad_fn=<AddmmBackward0>)

In [ ]:
import torch.nn.functional as F # mse loss built inside F

In [ ]:
loss_fn = F.mse_loss 

In [ ]:
loss = loss_fn(preds, targets)
loss

tensor(7131.0874, grad_fn=<MseLossBackward0>)

In [ ]:
# optimising parameters
opt = torch.optim.SGD(model.parameters(),lr = 1e-5)

In [ ]:
# train model
def fit(epochs, model, loss_fn, opt, train_dl):
  for epoch in range(epochs):
    for xs, ys in train_dl:
    ## GRADIENT DECENT
      pred = model(xs) # make predictions
      loss = loss_fn(pred, ys) # calculate loss
      loss.backward() # compute gradients
      opt.step() # update parameters using gradients
      opt.zero_grad() # reset the gradients to zero
      print("Loss:",loss.item())


In [ ]:
fit(100, model, loss_fn, opt, train_dl)

Loss: 6704.4013671875
Loss: 5752.91259765625
Loss: 3482.546142578125
Loss: 3700.25439453125
Loss: 1286.854248046875
Loss: 1730.0738525390625
Loss: 1433.0029296875
Loss: 767.98828125
Loss: 1518.218505859375
Loss: 1062.3961181640625
Loss: 1253.122314453125
Loss: 445.064208984375
Loss: 861.7987060546875
Loss: 661.09033203125
Loss: 883.7037963867188
Loss: 600.4296875
Loss: 1566.641357421875
Loss: 300.3280334472656
Loss: 589.390869140625
Loss: 604.5548095703125
Loss: 1054.889404296875
Loss: 400.72802734375
Loss: 634.7536010742188
Loss: 1109.791259765625
Loss: 118.4838638305664
Loss: 1092.879638671875
Loss: 773.48291015625
Loss: 747.9387817382812
Loss: 579.6634521484375
Loss: 578.1854248046875
Loss: 1014.1799926757812
Loss: 530.530517578125
Loss: 317.93536376953125
Loss: 589.5515747070312
Loss: 204.65243530273438
Loss: 979.9268798828125
Loss: 554.5426025390625
Loss: 455.82843017578125
Loss: 698.1793823242188
Loss: 542.7557983398438
Loss: 853.3435668945312
Loss: 265.4645080566406
Loss: 503.88

In [ ]:
preds = model(inputs)

In [ ]:
preds # closer to targets

tensor([[ 59.1862,  71.0391],
        [ 79.7838,  97.9234],
        [120.2268, 137.5645],
        [ 33.3165,  41.7373],
        [ 90.5584, 111.5492],
        [ 58.1784,  69.9740],
        [ 79.0758,  97.5069],
        [120.2979, 137.9097],
        [ 34.3242,  42.8024],
        [ 90.8581, 112.1978],
        [ 58.4781,  70.6226],
        [ 78.7761,  96.8584],
        [120.9349, 137.9810],
        [ 33.0168,  41.0887],
        [ 91.5661, 112.6143]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
# make pred for new input
new_inp = torch.tensor([75, 63, 44.0])
model(new_inp)

tensor([55.5692, 67.5790], grad_fn=<AddBackward0>)